.TH "IFFPP" "1" "January 2012" "iffpp 0.1" "Command Reference"
.SH "NAME"
iffpp \- Displays a textual representation of an IFF file on the standard output
.SH "SYNOPSIS"
\fBiffpp\fR [\fIoptions\fR] [\fIfile.IFF\fR]
.SH "DESCRIPTION"
.PP
The command \fBiffpp\fR displays a textual representation of a given IFF file,
which can be used for manual inspection. If no IFF file is specified, it reads
an IFF file from the standard input.
.SH "OPTIONS"
\fB\-c\fR, \fB\-\-disable\-check\fR
.RS 4
Do not check the IFF file for validity
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Shows the usage of this command to the user
.RE
.PP
.SH "AUTHOR"
.PP
\fBSander van der Burg\fR
.br
.RS 4
Author
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012 Sander van der Burg
.br
